### ISSUE TITLE
Make mina-puma compatible with mina 1.0.0

### ISSUE THREAD

**Issue by d4rky-pl** [untitledkingdom/mina-puma#12]
We have locked mina-puma to previous versions of mina with 8aa666bd73c349261f4d15a83764936e5f15e865 but we need to rewrite the gem to be compatible with mina 1.0.0.

**Comment by ghost** [comment]
👍

**Comment by scriptfans** [comment]
+1

**Comment by 1c7** [comment]
same here.

**Comment by stereodenis** [comment]
@d4rky-pl @dimosz @scriptfans @1c7 
try update to get this https://github.com/untitledkingdom/mina-puma/pull/15

**Comment by d4rky-pl** [comment]
Fixed by #15

**Comment by 1c7** [comment]
awesome, thanks @d4rky-pl @stereodenis
