### ISSUE TITLE
Missing `mina init` in README installation section

### ISSUE THREAD

**Issue by belgoros** [untitledkingdom/mina-puma#24]
It seems like the command
```
mina init
```
is missing in [Installation](https://github.com/untitledkingdom/mina-puma#installation) section, - you start the [Usage](https://github.com/untitledkingdom/mina-puma#usage) section directly with 
>Add this to your config/deploy.rb file:

But `config/deploy.rb` does not exist yet, - you will have to run `mina init` before to generate it.

**Comment by d4rky-pl** [comment]
True, we expected people coming to use this gem to have Mina already configured but I can see how can that be confusing to a total newcomer. Feel free to send a PR fixing this :)

**Comment by belgoros** [comment]
@d4rky-pl I have created https://github.com/sandelius/mina-puma/pull/24

**Comment by belgoros** [comment]
Is it OK to submit it there ou I have to submit it to `untitledkingdom` ?

**Comment by d4rky-pl** [comment]
@belgoros I'm afraid Sandelius didn't give us access to his repository and only added the redirect so you will have to send it here as well :)

**Comment by belgoros** [comment]
@d4rky-pl I submitted it https://github.com/untitledkingdom/mina-puma/pull/25 and closed this one: https://github.com/sandelius/mina-puma/pull/24

**Comment by lulalala** [comment]
#25 is merged so we can close this?

**Comment by belgoros** [comment]
Yep sure, thank you 😄
